package main

import (
	"context"
	"encoding/json"
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"time"

	"github.com/aws/aws-lambda-go/lambda"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"
	"go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
)

type Event map[string]interface{}

type Response struct {
	Message          string `json:"message"`
	Status           string `json:"status"`
	ProcessedRecords int64  `json:"processed_records"`
	RandomValue      int64  `json:"random_value"`
}

var (
	meterProvider *sdkmetric.MeterProvider

	invocationCounter       metric.Int64Counter
	successCounter          metric.Int64Counter
	errorCounter            metric.Int64Counter
	coldStartCounter        metric.Int64Counter
	processedRecordsCounter metric.Int64Counter
	cacheHitsCounter        metric.Int64Counter
	cacheMissesCounter      metric.Int64Counter

	durationHistogram        metric.Float64Histogram
	payloadSizeHistogram     metric.Int64Histogram
	externalAPIHistogram     metric.Float64Histogram
	databaseLatencyHistogram metric.Float64Histogram

	randomBusinessGauge   metric.Int64Gauge
	memoryConfiguredGauge metric.Int64Gauge

	isColdStart = true
)

func initMeterProvider(ctx context.Context) error {
	exporter, err := otlpmetrichttp.New(ctx)
	if err != nil {
		return fmt.Errorf("failed to create OTLP metric exporter: %w", err)
	}

	res, err := resource.Merge(
		resource.Default(),
		resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName("lambda-grafana-terraform"),
			semconv.ServiceVersion("1.0.0"),
			attribute.String("deployment.environment", "student-demo"),
			attribute.String("cloud.provider", "aws"),
			attribute.String("cloud.platform", "aws_lambda"),
			attribute.String("faas.name", "lambda"),
			attribute.String("project", "aws-lambda-grafana-terraform-otlp"),
		),
	)
	if err != nil {
		return fmt.Errorf("failed to create resource: %w", err)
	}

	reader := sdkmetric.NewPeriodicReader(
		exporter,
		sdkmetric.WithInterval(5*time.Second),
	)

	meterProvider = sdkmetric.NewMeterProvider(
		sdkmetric.WithResource(res),
		sdkmetric.WithReader(reader),
	)

	otel.SetMeterProvider(meterProvider)

	meter := otel.Meter("lambda-direct-grafana")

	invocationCounter, err = meter.Int64Counter(
		"lambda_invocations_total",
		metric.WithDescription("Total number of Lambda invocations"),
	)
	if err != nil {
		return err
	}

	successCounter, err = meter.Int64Counter(
		"lambda_success_total",
		metric.WithDescription("Total number of successful Lambda executions"),
	)
	if err != nil {
		return err
	}

	errorCounter, err = meter.Int64Counter(
		"lambda_errors_total",
		metric.WithDescription("Total number of Lambda errors"),
	)
	if err != nil {
		return err
	}

	coldStartCounter, err = meter.Int64Counter(
		"lambda_cold_starts_total",
		metric.WithDescription("Total number of Lambda cold starts"),
	)
	if err != nil {
		return err
	}

	processedRecordsCounter, err = meter.Int64Counter(
		"lambda_processed_records_total",
		metric.WithDescription("Total number of processed records by Lambda"),
	)
	if err != nil {
		return err
	}

	cacheHitsCounter, err = meter.Int64Counter(
		"lambda_cache_hits_total",
		metric.WithDescription("Total number of simulated cache hits"),
	)
	if err != nil {
		return err
	}

	cacheMissesCounter, err = meter.Int64Counter(
		"lambda_cache_misses_total",
		metric.WithDescription("Total number of simulated cache misses"),
	)
	if err != nil {
		return err
	}

	durationHistogram, err = meter.Float64Histogram(
		"lambda_duration_ms",
		metric.WithDescription("Lambda execution duration in milliseconds"),
	)
	if err != nil {
		return err
	}

	payloadSizeHistogram, err = meter.Int64Histogram(
		"lambda_payload_size_bytes",
		metric.WithDescription("Size of incoming Lambda event payload in bytes"),
	)
	if err != nil {
		return err
	}

	externalAPIHistogram, err = meter.Float64Histogram(
		"lambda_external_api_latency_ms",
		metric.WithDescription("Simulated external API latency in milliseconds"),
	)
	if err != nil {
		return err
	}

	databaseLatencyHistogram, err = meter.Float64Histogram(
		"lambda_database_latency_ms",
		metric.WithDescription("Simulated database latency in milliseconds"),
	)
	if err != nil {
		return err
	}

	randomBusinessGauge, err = meter.Int64Gauge(
		"lambda_random_business_value",
		metric.WithDescription("Current simulated business value generated by Lambda"),
	)
	if err != nil {
		return err
	}

	memoryConfiguredGauge, err = meter.Int64Gauge(
		"lambda_memory_configured_mb",
		metric.WithDescription("Configured Lambda memory size in MB"),
	)
	if err != nil {
		return err
	}

	return nil
}

func getMemorySizeMB() int64 {
	memoryValue := os.Getenv("AWS_LAMBDA_FUNCTION_MEMORY_SIZE")
	if memoryValue == "" {
		return 0
	}

	parsed, err := strconv.ParseInt(memoryValue, 10, 64)
	if err != nil {
		return 0
	}

	return parsed
}

func handler(ctx context.Context, event Event) (Response, error) {
	start := time.Now()

	if meterProvider == nil {
		if err := initMeterProvider(ctx); err != nil {
			return Response{
				Message: "OpenTelemetry initialization error",
				Status:  "error",
			}, err
		}
	}

	attrs := metric.WithAttributes(
		attribute.String("lambda_name", "lambda"),
		attribute.String("project", "aws-lambda-grafana-terraform-otlp"),
		attribute.String("environment", "student-demo"),
	)

	invocationCounter.Add(ctx, 1, attrs)

	if isColdStart {
		coldStartCounter.Add(ctx, 1, attrs)
		isColdStart = false
	}

	payloadBytes, _ := json.Marshal(event)
	payloadSize := int64(len(payloadBytes))
	payloadSizeHistogram.Record(ctx, payloadSize, attrs)

	processedRecords := int64(rand.Intn(20) + 1)
	randomBusinessValue := int64(rand.Intn(1000))
	externalAPILatency := float64(rand.Intn(300) + 50)
	databaseLatency := float64(rand.Intn(120) + 10)

	processedRecordsCounter.Add(ctx, processedRecords, attrs)
	externalAPIHistogram.Record(ctx, externalAPILatency, attrs)
	databaseLatencyHistogram.Record(ctx, databaseLatency, attrs)

	randomBusinessGauge.Record(ctx, randomBusinessValue, attrs)
	memoryConfiguredGauge.Record(ctx, getMemorySizeMB(), attrs)

	if rand.Intn(100) < 70 {
		cacheHitsCounter.Add(ctx, 1, attrs)
	} else {
		cacheMissesCounter.Add(ctx, 1, attrs)
	}

	if rand.Intn(100) < 10 {
		errorCounter.Add(ctx, 1, attrs)

		durationMs := float64(time.Since(start).Milliseconds())
		durationHistogram.Record(ctx, durationMs, attrs)

		if err := meterProvider.ForceFlush(ctx); err != nil {
			fmt.Fprintf(os.Stderr, "failed to flush metrics: %v\n", err)
		}

		return Response{
			Message:          "Lambda simulated error and sent metrics to Grafana Cloud",
			Status:           "simulated_error",
			ProcessedRecords: processedRecords,
			RandomValue:      randomBusinessValue,
		}, nil
	}

	successCounter.Add(ctx, 1, attrs)

	durationMs := float64(time.Since(start).Milliseconds())
	durationHistogram.Record(ctx, durationMs, attrs)

	if err := meterProvider.ForceFlush(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "failed to flush metrics: %v\n", err)
	}

	return Response{
		Message:          "Lambda sent extended metrics directly to Grafana Cloud",
		Status:           "ok",
		ProcessedRecords: processedRecords,
		RandomValue:      randomBusinessValue,
	}, nil
}

func main() {
	lambda.Start(handler)
}
